books/config/routes.rb
Rails.application.routes.draw do
  root :to => 'index#index'
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

books/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

books/app/models/book.rb
class Book < ApplicationRecord
  validates :year, numericality: { only_integer: true, greater_than_or_equal_to: 0 , allow_nil: true }
end

books/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_filter :set_locale
def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
end

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def default_url_options(options={})
     { :locale => I18n.locale }
  end
end

books/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  	http_basic_authenticate_with name: "admin", password: "admin", except: :index

  # GET /books
  # GET /books.json
  def index
    @books = Book.paginate(:page => params[:page], :per_page => 30)
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :genre, :year, :description, :read)
    end
end

books/app/controllers/index_controller.rb
class IndexController < ApplicationController

  def index
  end

end

books/app/helpers/application_helper.rb
module ApplicationHelper
end

books/app/helpers/books_helper.rb
module BooksHelper
end

books/app/views/books/_form.html.erb
<%= form_for @book, html: { class: 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :title, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :title, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :author, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :author, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :genre, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :genre, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :year, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :year, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :description, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :read, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :read, class: 'check_box form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, class: 'btn btn-primary' %>
      <%= link_to t('.cancel', default: t("helpers.links.cancel")),
                  books_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

books/app/views/books/edit.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

books/app/views/books/index.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= link_to t('.new', default: t("helpers.links.new")),
            new_book_path,
            class: 'btn btn-primary' %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:read) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:author) %></th>
      <th><%= model_class.human_attribute_name(:genre) %></th>
      <th><%= model_class.human_attribute_name(:year) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', default: t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
	<% if book.read == true %>
          <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
        <%end%>
	</td>
          <td><%= book.title %></td>
          <td><%= book.author %></td>
          <td><%= book.genre %></td>
          <td><%= book.year %></td>
          <td><%= book.description %></td>
        <td><%=l book.created_at, format: :long %></td>
        <td>
          <%= link_to book_path(book), class: 'btn btn-xs', title: "#{ t('.show', default: t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
          <%- end -%>
          <%= link_to edit_book_path(book), class: 'btn btn-xs', title: "#{ t('.edit', default: t('helpers.links.edit')) }" do %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to book_path(book), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-xs', title: "#{ t('.destroy', default: t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @books %>

books/app/views/books/new.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

books/app/views/books/show.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.titleize %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:title) %></dt>
      <dd><pre class="prettyprint"><%= @book.title %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:author) %></dt>
      <dd><pre class="prettyprint"><%= @book.author %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:genre) %></dt>
      <dd><pre class="prettyprint"><%= @book.genre %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:year) %></dt>
      <dd><pre class="prettyprint"><%= @book.year %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @book.description %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:read) %></dt>
      <dd><pre class="prettyprint"><%= @book.read %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', default: t("helpers.links.back")),
              books_path, class: 'btn btn-default'  %>
  <%= link_to t('.edit', default: t("helpers.links.edit")),
              edit_book_path(@book), class: 'btn btn-default' %>
  <%= link_to t('.destroy', default: t("helpers.links.destroy")),
              book_path(@book),
              method: 'delete',
              data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
              class: 'btn btn-danger' %>
</div>

books/app/views/index/index.html.erb
<div class="jumbotron">
	<div class="text-center">
		<h1>Lista książek!</h1>
		<p>Stwórz listę książęk do przeczytania.</p>
	</div>

</div>

books/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Books</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-fixed-top navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapsable">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/" class="navbar-brand"><%= t("main_title") %></a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapsable">
      <ul class="nav navbar-nav foo" id="menu">
        <li class="active"><a href="/books"><%= t("book_list_title") %></a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right" align="right">
        <li>
        <% if I18n.locale == I18n.default_locale %>
          <%= link_to "English", :locale=>'en'%>
        <% else %>
          <%= link_to "Polski", :locale=>'pl'%>
        <%end%>
      </li>
      </ul>
    </div>
  </div>
</nav>
    <%= yield %>
  </body>
</html>